version: '2'
services:
  zookeeper:
    container_name: DEV_zookeeper
    image: wurstmeister/zookeeper
    ports:
      - '2182:2182'
  kafka:
    container_name: DEV_kafka
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2182'
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_CREATE_TOPICS: "messages"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  db:
    image: postgres
    restart: always
    environment:
      POSTGERS_PASSWORD: r00tr00t
      POSTGRES_DB: LOT4
    ports:
      - '5432:5432'
  receiver-app:
    container_name: receiver-app
    image: 'receiver-app:1.0'
    environment:
       KAFKA_HOST: kafka:9092
       PG_URL: db:5432



